spring.application.name=gerenciadordespesas

# Desabilitar H2
# spring.datasource.url=jdbc:h2:mem:testdb

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/gerenciador_despesas
spring.datasource.username=postgres
spring.datasource.password=Flamengo27@
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Server Port Settings
server.port=8080

# JWT Secret
jwt.secret=${JWT_SECRET:minha-chave-secreta-muito-longa-e-aleatoria-para-o-projeto-gerenciador-de-despesas}
