# Configurações do perfil local de Desenvolvimento (dev) com H2
spring.datasource.url=jdbc:h2:mem:gerenciador_despesas;DB_CLOSE_DELAY=-1;MODE=MySQL
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Habilitar console do H2 para visualização do banco local
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Porta do Servidor Local
server.port=8080

# Segredo JWT local para desenvolvimento
jwt.secret=minha-chave-secreta-muito-longa-e-aleatoria-para-o-projeto-gerenciador-de-despesas-local-dev

# Configurações de cookie locais (HTTP)
cookie.secure=false
cookie.samesite=Lax

